### ISSUE TITLE
odd one - help needed

### ISSUE THREAD

**Issue by osaris775** [alexbn71/AgentDVR-Telegram#3]
Hi Alex thanks for your work on this, much appreciated.

I am fiddling with ispy/agentdvr. I am using your bash scripts. I have a tplink camera that supports onvif. 
I get the avgentdvr to record an event based on an onvif action if its triggered by the camera, but cant for the life of me get it agentdvr to trigger your sendphoto script if an onvif event occurs. 

I can however manually trigger the sendphoto script and it works 100%. 

![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/53944908/cfd96d29-aef6-4690-8765-76befe226792)

![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/53944908/7279425a-f41d-467b-aab0-c69b34014bab)

![image](https://github.com/alexbn71/AgentDVR-Telegram/assets/53944908/2255beab-10c7-4576-9138-da79a3c792c4)

I have logging set to debug but i am not getting anything useful, its as if its not triggering the script. Agentdvr is running in a container, and for most parts its running fine. I am not sure if this is a bug with the application, most prob it is, because i had to redefine the camera a couple of times after fiddling around to get the event recording to work. 

anyways thank you. if you have any ideas, please let me know. I am fairly new to ispy. Have been fooling around with it for a week or so. 

many thanks!
Osaris

**Comment by alexbn71** [comment]
Hi Osaris,

if the script is triggered by manual alert and it works on telegram I suppose that the issue is related to agentdvr and the onvif trigger. I never used this kind of trigger... Pheraps you could switch to agentdvr motion detection feature which is quite powerful. You might install and use an AI linked to agentdvr... like CodeProject.AI (docker) to extend detection to obejcts/persons or LPR
